dist: bionic

addons:
  apt:
    sources:
      - docker-bionic
    packages:
      - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y openjdk-8-jdk
  - wget https://services.gradle.org/distributions/gradle-5.5.1-bin.zip -P /tmp
  - sudo unzip -d /opt/gradle /tmp/gradle-*.zip
  - export GRADLE_HOME=/opt/gradle/gradle-5.5
  - export PATH=${GRADLE_HOME}/bin:${PATH}
  - unzip -o -d ./ test-server-develop.zip

script:
  - cd titan-server-develop-5f328e32d3440ff9116ff0c7da826c14e97a68eb && ./gradlew check assemble endtoendTest