version: 1.0.{build}
image: Windows Server 2019

build_script:
  - docker-switch-linux
  #- choco install unzip gradle graalvm
  #- mkdir -p /mnt/d/user-tmp/
  #- unzip -o -d /mnt/d/user-tmp/ test-server-develop.zip
  #- SET JAVA_HOME=C:\Program Files\GraalVM\graalvm-ce-19.1.0\jre
  #- SET GRAAL_BIN=C:\Program Files\GraalVM\graalvm-ce-19.1.0\bin
  #- SET PATH=%GRAAL_BIN%;%PATH%

test_script:
  - cd D:\
  - pwd
  - ls
  #- gradlew check assemble endtoendTest --info