version: 1.0.{build}
image: Windows Server 2019

build_script:
  - docker-switch-linux
  - choco install unzip gradle graalvm
  - docker build -t mcred/ubuntu-test .
  - unzip -o -d ./ test-server-develop.zip
  - SET JAVA_HOME=C:\Program Files\GraalVM\graalvm-ce-19.1.0\bin
  - SET PATH=%JAVA_HOME%\bin;%PATH%

test_script:
  - cd C:\Program Files\GraalVM\graalvm-ce-19.1.0\bin
  - ls
  - java -version
#  - cd titan-server-develop-b0dce9140dd903873a27be26bc1fc7bf02b6d53a
#  - gradlew check assemble endtoendTest