version: 1.0.{build}
image: Visual Studio 2017

install:
  - docker images --platform linux

#build_script:
#  - docker build -t mcred/ubuntu-test --platform linux .

#test_script:
#  - docker run --platform linux mcred/ubuntu-test